repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: ^(.*\/)?settings\.py$
        files: \.py$

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        additional_dependencies: ["click==8.0.4"]
        files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        files: \.py$
