// workflows.ts
export const workflows = [
  {
    id: "news-reporter",
    title: "News Reporter",
    description: "Stay updated with AI curated news, tailored to your interests.",
    highlight: "Stay updated with news tailored to your interests.",
    href: "/workflows/news-reporter",
    color: "bg-blue-200",
    inputs: [
      { label: "Preferred topics (e.g. tech, fashion)", required: true },
      { label: "Update frequency (daily, weekly)", required: false },
    ],
  },
  {
    id: "content-creator",
    title: "Content Creator",
    description: "Auto-generate engaging posts for any platform.",
    highlight: "Create consistent and engaging content in seconds.",
    href: "/workflows/content-creator",
    color: "bg-pink-200",
    inputs: [
      { label: "Platform (Instagram, LinkedIn, etc.)", required: true },
      { label: "Tone or brand voice", required: false },
      { label: "Post frequency", required: false },
    ],
  },
  {
    id: "review-master",
    title: "Review Master",
    description: "Collect, filter, and respond to reviews – automatically.",
    highlight: "Collect, filter, and respond to reviews – automatically.",
    href: "/workflows/review-master",
    color: "bg-green-200",
    inputs: [
      { label: "Business name", required: true },
      { label: "Review sources (Google, TripAdvisor)", required: true },
      { label: "Recipient email for negative reviews", required: true },
      { label: "LLM prompt for replying to positive reviews", required: false },
      { label: "Frequency (daily, weekly)", required: false },
    ],
  },
  {
    id: "guest-journey",
    title: "Guest Journey",
    description: "Deliver personalized emails at every stage of the guest journey.",
    highlight: "Deliver personalized emails across the entire guest journey.",
    href: "/workflows/guest-journey",
    color: "bg-yellow-200",
    inputs: [
      { label: "Guest stages (pre-arrival, post-stay, etc.)", required: true },
      { label: "Email templates or tone", required: false },
    ],
  },
  {
    id: "client-concierge",
    title: "Client Concierge",
    description: "Track and enhance buyer satisfaction from inquiry to close.",
    highlight: "Enhance client satisfaction across the buying journey.",
    href: "/workflows/client-concierge",
    color: "bg-orange-200",
    inputs: [
      { label: "Client journey touchpoints", required: true },
      { label: "Email or SMS templates", required: false },
    ],
  },
  {
    id: "social-media-scraper",
    title: "Social Media Scraper",
    description: "Extract posts, trends, and insights from any social platform.",
    highlight: "Uncover trends and track conversations across platforms.",
    href: "/workflows/social-media-scraper",
    color: "bg-purple-200",
    inputs: [
      { label: "Keywords or hashtags to track", required: true },
      { label: "Platform(s) (Twitter, Reddit, etc.)", required: true },
      { label: "Output format", required: false },
    ],
  },
  {
    id: "company-researcher",
    title: "Company Researcher",
    description: "Scrape recent news and summarize social media.",
    highlight: "Stay ahead with company-level insights from multiple sources.",
    href: "/workflows/company-researcher",
    color: "bg-teal-200",
    inputs: [
      { label: "Company name(s)", required: true },
      { label: "Data sources (news, LinkedIn, etc.)", required: false },
    ],
  },
  {
    id: "talent-finder",
    title: "Talent Finder",
    description: "Find the right talent faster with automated candidate matching.",
    highlight: "Get matched with top candidates in seconds.",
    href: "/workflows/talent-finder",
    color: "bg-violet-200",
    inputs: [
      { label: "Job title or role", required: true },
      { label: "Required skills or experience", required: true },
      { label: "LinkedIn account (optional)", required: false },
    ],
  },
  {
    id: "receipt-tracker",
    title: "Receipt Tracker",
    description: "Effortlessly log and organize receipts from email or uploads.",
    highlight: "Organize receipts automatically from all sources.",
    href: "/workflows/receipt-tracker",
    color: "bg-sky-200",
  },
  {
    id: "lead-generator",
    title: "Lead Generator",
    description: "Generate leads with Google Maps.",
    highlight: "Find and enrich leads directly from Google Maps.",
    href: "/workflows/lead-generator",
    color: "bg-sky-200",
    inputs: [
      { label: "Target location", required: true },
      { label: "Business type or keywords", required: true },
      { label: "Output format", required: false },
    ],
  },
  {
    id: "campaign-sender",
    title: "Campaign Sender",
    description: "Bulk-send emails and follow up automatically if no reply.",
    highlight: "Send personalized campaigns and follow up — automatically.",
    href: "/workflows/campaign-sender",
    color: "bg-red-200",
    inputs: [
      { label: "Recipient list (CSV or Airtable)", required: true },
      { label: "Email content or prompt", required: true },
      { label: "Follow-up rules", required: false },
    ],
  },
  {
    id: "inbox-sorter",
    title: "Inbox Sorter",
    description: "Sort your Gmail automatically with AI labels.",
    highlight: "Organize your inbox with AI in real-time.",
    href: "/workflows/inbox-sorter",
    color: "bg-purple-200",
    inputs: [
      { label: "Labels to apply (e.g. invoices, clients)", required: true },
      { label: "Gmail account connection", required: true },
      { label: "Optional rules or prompts", required: false },
    ],
  },
];
